services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: "teamcity"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  teamcity-server:
    image: jetbrains/teamcity-server
    environment:
      TEAMCITY_SERVER_MEM_OPTS: "-Xmx2g -XX:ReservedCodeCacheSize=512m"
      TEAMCITY_DATABASE_TYPE: "mysql"
      TEAMCITY_DATABASE_URL: "jdbc:mysql://db:3306/teamcity?useSSL=false&allowPublicKeyRetrieval=true"
      TEAMCITY_DATABASE_USERNAME: "root"
      TEAMCITY_DATABASE_PASSWORD: your_password
    volumes:
      - teamcity_data:/data/teamcity_server/datadir
      - teamcity_logs:/opt/teamcity/logs
      - .:/project
    ports:
      - "8111:8111"
  teamcity-agent:
    image: jetbrains/teamcity-agent
    environment:
      SERVER_URL: "http://teamcity-server:8111"
    depends_on:
      - teamcity-server
    volumes:
      - .:/app

  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_WEB_CONTEXT: /sonarqube
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
  sonar_db:
    image: postgres:15
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data

  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
      - "8085:8085"

volumes:
  # db_data:
  # m2_cache:
  teamcity_data:
  teamcity_logs:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
  nexus-data: {}